// Generates product/site/ru/index.html from product/site/index.html.
// The /ru/ entry exists so link previews (Telegram, WhatsApp, iMessage) show Russian
// title/description/image — crawlers don't run JS. The app itself is the same file.
// Run: node operations/build-ru.mjs   (CI runs it before every deploy)
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const site = join(dirname(fileURLToPath(import.meta.url)), '..', 'product', 'site');
let html = await readFile(join(site, 'index.html'), 'utf8');

const swaps = [
  ['<html lang="en">', '<html lang="ru" data-lang="ru">'],
  ['<head>\n', '<head>\n<base href="../">\n'],
  [/<meta name="description" content="[^"]*">/, '<meta name="description" content="Звёзды выдвинули гипотезу о твоих ценностях. 9 странных выборов её проверят. Компас ценностей за 3 минуты — честно, странно, не предсказание.">'],
  [/<meta property="og:title" content="[^"]*">/, '<meta property="og:title" content="BORN WEIRD — звёзды угадали твои ценности? Проверь за 3 минуты">'],
  [/<meta property="og:description" content="[^"]*">/, '<meta property="og:description" content="9 странных выборов: твой компас ценностей, главное противоречие и в чём ошиблись звёзды — на пиксельной карточке.">'],
  [/<meta property="og:image" content="[^"]*">/, '<meta property="og:image" content="https://dimacloud.github.io/born-weird/og-ru.png">\n<meta property="og:locale" content="ru_RU">'],
];
for (const [a, b] of swaps) {
  const before = html;
  html = html.replace(a, b);
  if (html === before) throw new Error('build-ru: pattern not found: ' + a);
}
html = html.replace('<!doctype html>\n', '<!doctype html>\n<!-- GENERATED by operations/build-ru.mjs from ../index.html. Do not edit. -->\n');
await mkdir(join(site, 'ru'), { recursive: true });
await writeFile(join(site, 'ru', 'index.html'), html);
console.log('wrote product/site/ru/index.html');
